/**
 * English source strings generated by `lib/enginea.ts`.
 *
 * Split into its own file so several authors can add engine messages without
 * colliding in one catalog; `lib/i18n/en.ts` merges them. Same rules as the
 * UI catalog: `{param}` slots carry FACTS (names, distances, counts) and are
 * never translated; plural variants are separate keys.
 *
 * Engine A's prose branches on what it found — a mismatch resting on one word
 * reads differently from one resting on six, a self-contradicting page reads
 * differently from a merely displaced one. Those are whole separate sentences
 * here rather than a stem plus an appended clause, because a translator needs
 * to move the qualifier to wherever their language puts it.
 */
export const engineaMessages = {
  // --- A1: URL slug vs displayed name ---
  'enginea.a1.notComparable.title': 'Slug and name are not comparable',
  'enginea.a1.notComparable.detail':
    'URL slugs on this platform are Latin script, and this property name has no Latin-script words, so the two share no comparable tokens by construction. The check was skipped rather than scored as a mismatch.',
  'enginea.a1.noIdentityWords.title': 'The property name carries no identifying words',
  'enginea.a1.noIdentityWords.detail':
    'This name is made up entirely of category words, so whether the slug repeats them says nothing about which property is being sold. The check could not be applied.',
  'enginea.a1.title': 'The URL slug does not match the property name',
  'enginea.a1.detail':
    'The platform builds the slug from the property name when the listing is created and keeps it through later renames. This slug describes a different property from the one on display, which is what a repurposed listing looks like.',
  // The thin variant: the whole accusation rests on a single identifying word.
  'enginea.a1.titleThin': 'The URL slug does not match the one identifying word in the name',
  'enginea.a1.detailThin':
    'The platform builds the slug from the property name when the listing is created and keeps it through later renames. This slug describes a different property from the one on display, which is what a repurposed listing looks like. The name has only one identifying word, so this is a single-word disagreement — reported, but not on its own enough to condemn the listing.',

  // --- A2: nearby landmarks vs coordinates ---
  'enginea.a2.unverified.title': 'Could not verify the listing against nearby landmarks',
  'enginea.a2.unverified.detail':
    'Checking the geography needs at least {min} landmarks that resolve to coordinates; this page did not supply them, or they could not be looked up. The location is unverified — that is not the same as verified-correct.',
  'enginea.a2.contradicted.title': 'The page contradicts itself about how close its landmarks are',
  'enginea.a2.contradicted.detail':
    'Each landmark below was located independently and measured from the coordinates this listing publishes. The distances the page prints do not survive that measurement, so the neighbourhood description belongs to a different property.',
  'enginea.a2.displaced.title': 'The landmarks this page calls nearby are nowhere near it',
  'enginea.a2.displaced.detail':
    'Every landmark this page advertises as nearby was located independently and measured from the coordinates the listing publishes. They are not in the same place.',

  // --- A3: breadcrumb city vs coordinates ---
  'enginea.a3.unresolved.title': 'Could not check the breadcrumb city',
  'enginea.a3.unresolved.detail':
    'The place named in the page trail could not be located, so there was nothing to compare against the coordinates the listing publishes.',
  // The lookup came back, and came back wrong: an answer that sits far from the
  // listing AND belongs to a hierarchy the trail never mentions is evidence
  // about the geocoder, not about the property. A separate sentence from
  // "could not be located", because a reader deciding whether to trust this
  // listing needs to know the difference between a question nobody answered and
  // an answer we threw out.
  'enginea.a3.inconsistent.title': 'Could not confirm where the page files this property',
  'enginea.a3.inconsistent.detail':
    'The place named in the page trail was looked up, and the coordinates that came back are for somewhere the trail does not mention. A lookup that lands in the wrong place says nothing about this listing, so it was dropped instead of counted against it.',
  'enginea.a3.title': 'The breadcrumb city does not match the map coordinates',
  'enginea.a3.detail':
    'The page files this property under a place in its navigation trail. That place was located independently — the trail names it too — and it is a long way from the coordinates the same page publishes.',

  // --- shared failure paths ---
  // One title, two details: what there was nothing to measure *against* is a
  // noun inside the sentence, so each rule states its own rather than having a
  // fragment posted in as a parameter.
  'enginea.noCoordinates.title': 'The listing publishes no usable coordinates',
  'enginea.noCoordinates.detail.landmarks':
    'Without coordinates for the property there is nothing to measure landmark geography against. (0, 0) counts as missing: it is open ocean, and a property placed there has an empty coordinate field rather than a location.',
  'enginea.noCoordinates.detail.breadcrumbCity':
    'Without coordinates for the property there is nothing to measure the breadcrumb city against. (0, 0) counts as missing: it is open ocean, and a property placed there has an empty coordinate field rather than a location.',
  'enginea.checkFailed.title.slugVsName': 'Slug vs name could not be checked',
  'enginea.checkFailed.title.landmarkGeography': 'Nearby-landmark geography could not be checked',
  'enginea.checkFailed.title.breadcrumbCity': 'Breadcrumb city could not be checked',
  'enginea.checkFailed.detail':
    'This check failed to complete, so it contributed nothing to the verdict.',

  // --- evidence-table values that are our own prose ---
  // The measurement is the fact and rides in as a bare number; the unit is a
  // word and lives here
  // "Coordinates moved {km} km since…"). A locale that abbreviates kilometres
  // differently, spaces them differently or puts the unit before the number can
  // then say so — which it could not if "437.0 km" arrived pre-assembled.
  // Everything else around the numbers — the threshold aside, the "of … looked
  // up", the landmark sentence — is ours to translate too.
  'enginea.value.overlapFlagged': '{overlap} (flagged below {threshold})',
  'enginea.value.landmarksLocatedOf': '{located} of {lookedUp} looked up',
  'enginea.value.distanceApartFlagged': '{distance} km (flagged above {threshold} km)',
  // A row whose whole value is one distance.
  'enginea.value.distanceKm': '{km} km',
  // A distance we could not compute is a word, not a quantity.
  'enginea.value.distanceUnknown': 'unknown',
  // One landmark, measured. `matched` is the geocoder's own name for what it
  // found — provider data, passed through untranslated. The two shapes are
  // separate sentences because a page that stated a distance and one that
  // stayed silent are different claims, not one claim with a hole in it.
  'enginea.value.landmarkRow.stated': '{real} km away — page says {stated} km — found: {matched}',
  'enginea.value.landmarkRow.noDistance':
    '{real} km away — no distance stated — found: {matched}',

  // --- evidence-table labels ---
  'enginea.value.urlSlug': 'URL slug',
  'enginea.value.displayedName': 'Displayed name',
  'enginea.value.slugWords': 'Slug words',
  'enginea.value.nameWordsCompared': 'Name words compared',
  // The check compares the two as words and, because platforms publish slugs
  // with the separators taken out ("lecolise" for "Le Colisée"), as one run of
  // letters as well. Both rows are shown so the table states what was actually
  // compared: when A1 fires, neither reading found the name in the slug.
  'enginea.value.slugRunTogether': 'Slug run together',
  'enginea.value.nameRunTogether': 'Name run together',
  'enginea.value.overlap': 'Overlap',
  'enginea.value.identityWords': 'Identity words in the name',
  'enginea.value.listingCoordinates': 'Listing coordinates',
  'enginea.value.landmarksOnPage': 'Landmarks on the page',
  'enginea.value.landmarksLookedUp': 'Landmarks looked up',
  'enginea.value.landmarksLocated': 'Landmarks located',
  'enginea.value.medianRealDistance': 'Median real distance',
  'enginea.value.medianGap': 'Median gap vs the stated distance',
  // These two keep their key names and change their words, because what the
  // rows hold changed: A3 no longer picks one entry out of the trail and
  // geocodes it, it asks about the qualified path ("6e arr., Paris,
  // Île-de-France") and prints the query verbatim, and what comes back may be a
  // district or a landmark inside the city rather than the city. A label that
  // still said "Breadcrumb city" would describe something the check no longer
  // does. (`scripts/translate-catalog.ts` hashes the English per key, so both
  // are re-translated on the next run rather than left silently stale.)
  'enginea.value.breadcrumbCity': 'Breadcrumb place looked up',
  'enginea.value.cityLocatedAt': 'Place located at',
  'enginea.value.distanceApart': 'Distance apart',
  'enginea.link.map': 'These coordinates on a map',
} as const;
