/**
 * English source strings generated by `lib/enginel.ts`.
 *
 * Split into its own file so several authors can add engine messages without
 * colliding in one catalog; `lib/i18n/en.ts` merges them. Same rules as the
 * UI catalog: `{param}` slots carry FACTS (names, distances, counts) and are
 * never translated; plural variants are separate keys.
 *
 * Engine L reads attacker-influenceable page text through a local model, so
 * one extra rule applies here: nothing the model produced is ever a key. The
 * catalog holds only the frame we authored; every model-derived string —
 * claims, fields, amenities, reasons, quotes — arrives as a `{param}` or as a
 * quoted value and passes through untranslated. A page that could choose our
 * catalog keys could choose the sentence the panel shows.
 */
export const enginelMessages = {
  // L2 — reviews contradicting the claimed identity.
  'enginel.l2.title': 'Guest reviews contradict the listing’s claimed identity',
  // Three plural forms, per the catalog convention. English sidesteps
  // agreement with "place(s)" and so reads the same in all of them; pl/ru/uk
  // bend at 2-4 and need `few` to be its own string.
  //
  // The engine can only ever CHOOSE between `one` and `many`: `selectPlural`
  // reads the active panel language and the service worker has none, so
  // `lib/enginel.ts` picks by the rule English needs. `few` is therefore never
  // selected engine-side and exists for the panel to re-select — which it can,
  // because every variant is emitted carrying `count`. Until it does, a Slavic
  // reader sees the `many` form for 2-4: wrong ending, right sentence.
  //
  // `one` hardcodes the digit rather than taking a slot, matching
  // `search.status.resultsOne`. That is safe only because
  // MAX_L2_CONTRADICTIONS caps the count at 6, so the `one` category can never
  // mean 21 or 31 the way it does in Russian for unbounded counts.
  'enginel.l2.detailOne':
    'A local language model found 1 place(s) where the page text disagrees with the identity the listing claims. Each quote below was verified to appear on the page. This is a suggestion, not a finding: it cannot raise the verdict on its own.',
  'enginel.l2.detailFew':
    'A local language model found {count} place(s) where the page text disagrees with the identity the listing claims. Each quote below was verified to appear on the page. This is a suggestion, not a finding: it cannot raise the verdict on its own.',
  'enginel.l2.detailMany':
    'A local language model found {count} place(s) where the page text disagrees with the identity the listing claims. Each quote below was verified to appear on the page. This is a suggestion, not a finding: it cannot raise the verdict on its own.',
  // The whole authored content of this label is the colon: `field` and `claim`
  // are both model output, carried as facts and never looked up.
  'enginel.l2.evidenceLabel': '{field}: {claim}',

  // L3 — an implausible combination of advertised amenities.
  'enginel.l3.title': 'The advertised amenities look implausible together',
  'enginel.l3.detail':
    'A local language model considered this combination of amenities unusual for this property type and location. Weak evidence on its own — plenty of genuine listings are unusual — but it is a known pattern in copied listing text.',
} as const;
