/**
 * English source strings generated by `lib/reviewscan.ts`.
 *
 * Split into its own file so several authors can add engine messages without
 * colliding in one catalog; `lib/i18n/en.ts` merges them. Same rules as the
 * UI catalog: `{param}` slots carry FACTS (counts, scores, ages) and are never
 * translated; plural variants are separate keys.
 *
 * Two habits from `./terms.ts` carry over, and one is new to this file.
 *
 * Carried over: a sentence that varies by circumstance gets one key per whole
 * sentence rather than a fragment spliced into a shared one, and numbers that
 * need grouping or a decimal point travel twice — `{total}` already formatted
 * for display, plus a `…Value` twin with no slot, so a panel can re-format the
 * raw number in the reader's own locale (3.526 / 3 526) and pass the result
 * back under the SAME slot name. The `…Value` twins are inert in English and
 * cost nothing; note that a locale cannot switch its text to them, because
 * `lib/i18n.test.ts` requires every locale's placeholder set to match
 * English's exactly.
 *
 * New here: the AGE phrases are deliberately tiny and standalone ("8 months
 * ago"), not sentences with an age spliced in. An age appears in several
 * places — beside the oldest review, beside each surfaced one — and the unit
 * word is the only part that needs translating. This is the same shape as
 * `search.radius.km` in the UI catalog, for the same reason.
 *
 * What is NOT here: review text. A guest's words and the sentence a match was
 * found in are quoted verbatim and never keyed — a translated quote is not
 * evidence, and this module's whole claim to honesty is that every pointer can
 * be checked against the text printed beside it.
 */
export const reviewsMessages = {
  // --- the section, and the standing limit on everything inside it ---------
  'reviews.section.title': 'What guests wrote',
  // Said once, plainly, because everything below is weaker than it looks.
  'reviews.limits.advisory':
    'Guest reviews never move the verdict. They are written by other people and chosen by the platform, so a planted review must not be able to accuse an honest property — nor a flattering one clear a dishonest listing. What follows is here to be read, not scored.',

  // --- the sample: how little of it we saw --------------------------------
  'reviews.sample.ofTotal':
    'Read {shown} of the {total} reviews this page claims — the ones it chose to show. Platforms serve a handful and pick which handful, so treat this as a shop window, not a sample.',
  'reviews.sample.totalUnknown':
    "Read {shown} of the page's reviews — the ones it chose to show. It does not say how many exist in total, so there is no telling what share of them this is.",
  'reviews.sample.none':
    'The page served no guest reviews, so there was nothing to read. That is not a clean record; it is no record.',

  // --- curation, measured on this page rather than asserted ----------------
  'reviews.curation.featuredHigher':
    "The reviews on display average {featured} out of 10, above the property's own overall score of {overall}. The gap is the selection at work: the page is showing you its better reviews.",

  // --- the window: what could never have reached us ------------------------
  'reviews.window.oldest':
    'That is as far back as this page lets anyone see. A complaint older than the oldest review here leaves no trace in this panel — not because nothing happened, but because the page does not serve reviews that old.',
  'reviews.window.noDates':
    'The page served no dates with these reviews, so there is no telling whether they describe last month or three years ago.',

  // --- coverage of the word check -----------------------------------------
  'reviews.language.uncoveredOne':
    'One review is written in a language this word check does not cover, so only its score was read.',
  'reviews.language.uncoveredMany':
    '{count} of these reviews are written in a language this word check does not cover, so only their scores were read.',

  // --- nothing found is not the same as nothing wrong ----------------------
  'reviews.none.flagged':
    'Nothing stood out in the reviews the page served. They are the page\'s own selection, so this is not a clean bill of health — it is the absence of one.',

  // --- why a single review was surfaced ------------------------------------
  // The score is shown on the platform's own scale, because that is what the
  // guest actually chose: 1 out of 5 and 1 out of 10 are different claims, and
  // converting one into the other quietly rewrites what the person said.
  'reviews.reason.lowScore':
    'Scored {score} out of {max} — the bottom half of the scale this platform offers.',
  // One key per category, each one warning about its own failure mode. A word
  // is a pointer to a sentence worth reading, never a finding on its own.
  'reviews.match.fraud':
    'This review uses a word for a scam or a fraud. Read the quote before concluding anything: a guest may be describing a price dispute, a taxi driver, or another property entirely.',
  'reviews.match.nonexistent':
    'This review says something did not exist. Read the quote to see what: the address, the property itself, or a facility the listing advertised.',
  'reviews.match.misrepresented':
    'This review says what the guest found did not match what the listing showed. Read the quote and judge it yourself.',

  // Where in the review the words were found. Booking splits a review into a
  // liked and a disliked box, and which box a complaint sits in is part of
  // reading it — guests routinely type the complaint into the wrong one.
  'reviews.field.positive': 'From the "liked" part of the review',
  'reviews.field.negative': 'From the "disliked" part of the review',
  'reviews.field.title': 'From the review title',

  // --- ages, as standalone phrases -----------------------------------------
  // Plain facts with a unit. No decay, no weighting: the reviews a page serves
  // are months old, not years, so any curve fitted past that would be drawn
  // through no measurements at all.
  'reviews.age.dayZero': 'today',
  'reviews.age.dayOne': '1 day ago',
  'reviews.age.dayMany': '{count} days ago',
  'reviews.age.monthOne': '1 month ago',
  'reviews.age.monthMany': '{count} months ago',
  'reviews.age.yearOne': '1 year ago',
  'reviews.age.yearMany': '{count} years ago',
  'reviews.age.unknown': 'date not given',
} as const;
