/**
 * English source strings generated by `lib/score.ts`.
 *
 * Split into its own file so several authors can add engine messages without
 * colliding in one catalog; `lib/i18n/en.ts` merges them. Same rules as the
 * UI catalog: `{param}` slots carry FACTS (names, distances, counts) and are
 * never translated; plural variants are separate keys.
 *
 * Two conventions specific to this file:
 *
 *  - `{title}` is a signal's own one-line statement. The scorer fills it with
 *    the English title so `english()` renders a whole sentence; the panel
 *    refills it from that signal's `titleMsg` in the reader's language, using
 *    the `{id}` slot to find the signal. Nothing here holds a second copy of
 *    an engine's words.
 *  - Where a sentence differs only by which engine it names ("LLM" vs the
 *    generic "untrusted"), the two are separate keys rather than one key with
 *    the word as a param: the word is part of the sentence and has to decline
 *    with it.
 */
export const scoreMessages = {
  // Verdict reasons, in the order `score()` emits them.
  'score.reason.deterministicRed': 'RED from deterministic rule {id}: {title}',
  'score.reason.llmRedPromoted':
    'RED from LLM rule {id}: {title} — promoted because deterministic {support} corroborates it.',
  'score.reason.untrustedRedPromoted':
    'RED from untrusted rule {id}: {title} — promoted because deterministic {support} corroborates it.',
  'score.reason.deterministicYellow': 'YELLOW from deterministic rule {id}: {title}',
  'score.reason.llmYellow': 'YELLOW from LLM rule {id}: {title}',
  'score.reason.untrustedYellow': 'YELLOW from untrusted rule {id}: {title}',
  'score.reason.llmFlaggedUncounted':
    '{id} (LLM) flagged: {title} — noted, not counted, because no deterministic rule agreed. Page text alone cannot move the verdict.',
  'score.reason.untrustedFlaggedUncounted':
    '{id} (untrusted) flagged: {title} — noted, not counted, because no deterministic rule agreed. Page text alone cannot move the verdict.',
  'score.reason.llmProposedRedUncounted':
    '{id} (LLM) proposed RED with no deterministic rule to corroborate it — noted, not counted. Page text alone cannot move the verdict.',
  'score.reason.untrustedProposedRedUncounted':
    '{id} (untrusted) proposed RED with no deterministic rule to corroborate it — noted, not counted. Page text alone cannot move the verdict.',
  'score.reason.green': 'GREEN: every rule that could run passed, and the live identity was complete.',
  'score.reason.grayIdentityIncomplete':
    'GRAY: the live identity was incomplete — the page did not yield the fields the deterministic rules need. This is "not checked", not "clean".',
  'score.reason.grayUninterpretable':
    'GRAY: the scorer was handed input it could not interpret, so it cannot say this listing was checked. This is "not checked", not "clean".',
  'score.reason.identityIncomplete':
    'Identity incomplete: some fields the deterministic rules need were missing, so this verdict rests on a partial read of the page.',
  'score.reason.couldNotCheck':
    'Could not check: {ids} — an unknown is never counted as agreement.',
  'score.reason.noSignals':
    'Could not check: the scorer was not handed a list of signals at all, so nothing about this listing was actually evaluated.',
  'score.reason.coverage':
    'Coverage: {ran} of {total} checks ran on this page — the rest are listed under the verdict with the reason each one could not.',

  // Coverage rows. Labels are standalone noun phrases: the panel composes the
  // row title from the label plus a status word it translates itself, so a
  // label must never carry punctuation or a verb that assumes what follows.
  'score.coverage.a1.label': 'Web address vs displayed name',
  'score.coverage.a1.notApplicable':
    "this platform's listing addresses carry no property name to compare",
  'score.coverage.a1.noSlug': 'the address had no readable name part',
  'score.coverage.a2.label': 'Nearby landmarks vs the map',
  'score.coverage.a2.notApplicable': "this platform's pages list no nearby landmarks",
  'score.coverage.a2.noLandmarks': 'the page listed no nearby landmarks',
  'score.coverage.a2.noLocation': 'the page gave no location to measure from',
  'score.coverage.a3.label': 'Breadcrumb trail vs the map',
  'score.coverage.a3.noBreadcrumbs': 'the page had no breadcrumb trail to read',
  'score.coverage.a3.noCoordinates': 'the page gave no coordinates to compare against',
} as const;
