/**
 * English source strings generated by `lib/terms.ts`.
 *
 * Split into its own file so several authors can add engine messages without
 * colliding in one catalog; `lib/i18n/en.ts` merges them. Same rules as the
 * UI catalog: `{param}` slots carry FACTS (names, distances, counts) and are
 * never translated; plural variants are separate keys.
 *
 * Every advisory that varies by circumstance gets one key per whole sentence
 * rather than a spliced fragment: "…public street parking near the property
 * that cannot be reserved" is a different sentence from "…public parking near
 * the property", not the same sentence with a word inserted, and only a
 * language that happens to share English word order could translate the
 * splice. The `quote` field carries verbatim page text and never appears
 * here — a page's own words are evidence, not something we author.
 */
export const termsMessages = {
  // T.parking — free parking the property does not own and cannot promise.
  'terms.parking.title': 'The "free parking" is public parking, not the property\'s own',
  'terms.parking.detail':
    'The page advertises free parking, but its own small print says this is public parking near the property. Nobody can hold a public space for you, so it may simply not be available when you arrive — worth knowing if you are counting on it.',
  'terms.parking.detailUnreservable':
    'The page advertises free parking, but its own small print says this is public street parking near the property that cannot be reserved. Nobody can hold a public space for you, so it may simply not be available when you arrive — worth knowing if you are counting on it.',

  // T.cancellation — money committed from the moment of booking.
  'terms.cancellation.title': 'Cancelling this booking costs real money from the start',
  'terms.cancellation.titleNonRefundable':
    'No free cancellation — every displayed rate is non-refundable',
  'terms.cancellation.detail':
    'Plans change; this booking does not. If the trip falls through, the money is already committed. Check whether a slightly pricier refundable rate exists before choosing this one.',
  // Three facts, no sentences. `{amount}` is the figure already grouped for
  // display, and is the only slot this text has — which is what keeps the
  // English rendering frozen. `amountValue` is the SAME figure unformatted
  // (450, 15000) and has NO slot; `fill()` ignores a param with no slot, so it
  // costs nothing to carry.
  //
  // It is there so the panel can group the number in the reader's own locale
  // instead of showing English grouping (15,000) inside a Russian or German
  // sentence. The panel does that by formatting `amountValue` itself and
  // passing the result AS `amount` — every locale's text keeps the `{amount}`
  // slot and nothing else changes. Note that translations cannot simply switch
  // their own text to `{amountValue}`: the catalog-integrity test in
  // `lib/i18n.test.ts` requires each locale's placeholder set to match
  // English's exactly, so substituting the slot would fail CI.
  //
  // `currency` is the page's own code, passed through untouched.
  'terms.cancellation.detailWithFee':
    'Plans change; this booking does not. If the trip falls through, the money is already committed. The stated cancellation cost is {amount} {currency}. Check whether a slightly pricier refundable rate exists before choosing this one.',

  // T.payment — irreversible, off-platform money movement.
  'terms.payment.transferTitle': 'Payment by bank transfer requested',
  'terms.payment.transferFullTitle': 'Full prepayment by bank transfer requested',
  'terms.payment.transferDetail':
    'A bank transfer is irreversible: unlike a card payment, there is no chargeback if the property is not what it claims. Asking for a transfer is also how hijacked-listing scams collect — it is the one payment method that cannot be undone. Small legitimate guesthouses do use transfers, so this alone proves nothing; but verify the property through a second channel before sending anything, and prefer a card if one is accepted.',
  'terms.payment.transferFullDetail':
    'A bank transfer is irreversible: unlike a card payment, there is no chargeback if the property is not what it claims. Asking for the whole amount up front by transfer is also how hijacked-listing scams collect — it is the one payment method that cannot be undone. Small legitimate guesthouses do use transfers, so this alone proves nothing; but verify the property through a second channel before sending anything, and prefer a card if one is accepted.',
  'terms.payment.prepaymentTitle': 'The full amount is charged before you arrive',
  'terms.payment.prepaymentDetail':
    'The property takes the whole payment in advance. Combined with a strict cancellation policy this means the money is committed the moment you book.',
} as const;
