/**
 * UI-chrome translations. English is the source of truth (`lib/i18n/en.ts`);
 * the other catalogs are MACHINE-TRANSLATED at build time by
 * `scripts/translate-catalog.ts` and committed as JSON — the extension never
 * contacts a translation service at runtime, because "nothing you view
 * leaves your machine" is a shipped promise, not a preference.
 *
 * Scope, stated honestly: this covers the chrome the extension itself draws
 * (search page, options page, panel headings and buttons). The evidence
 * prose generated by the engines still arrives in English — making signals
 * carry message keys is ROADMAP's deep i18n item, and pretending a catalog
 * this size covers it would be a lie in fourteen languages.
 *
 * A missing or mangled translation falls back to English per string — a
 * verdict UI must never show a blank where a word failed to arrive.
 */

import { en } from './i18n/en';
import { locales } from './i18n/locales';

// One definition, in `./i18n/keys`, so the engines can import the type without
// importing this module's fourteen locale catalogs. Re-exported here because
// the UI has always imported it from `lib/i18n` and should keep being able to.
export type { MessageKey } from './i18n/keys';
import type { MessageKey } from './i18n/keys';

export { SUPPORTED_LANGUAGES, isSupportedLanguage } from './i18n/languages';

let active: Partial<Record<MessageKey, string>> = {};
let activeCode = '';

/**
 * BCP-47 tag of the active language, for `Intl` formatting (month and
 * weekday names come from the platform, not the catalog). '' means English.
 */
export function activeLanguageTag(): string {
  return activeCode === '' ? 'en' : activeCode;
}

/**
 * Select the catalog for this page. '' (English) and unknown codes both land
 * on the English source — unknown must not throw, because the value crosses
 * storage and an old store may hold a code a newer build dropped.
 */
export function activateLanguage(code: string): void {
  active = code === '' ? {} : (locales[code] ?? {});
  activeCode = code !== '' && locales[code] !== undefined ? code : '';
}

/**
 * Look up a message and fill its `{param}` slots. Untranslated keys fall
 * back to English; unfilled params stay visible as `{name}` rather than
 * vanishing, so a missing argument is a bug one can see and report.
 */
export function t(key: MessageKey, params?: Record<string, string | number>): string {
  // `||`, not `??`: an empty-string translation (a generator bug the script
  // now also guards against) must fall back to English, never blank the UI.
  const template = active[key] || en[key];
  return template.replace(/\{(\w+)\}/g, (match: string, name: string) =>
    params !== undefined && params[name] !== undefined ? String(params[name]) : match,
  );
}

/**
 * Pick the plural key for a count in the ACTIVE language, via the platform's
 * own plural rules — pl/ru/uk bend at 2-4 ("2 ночи" is the `few` form, and
 * a two-form catalog renders it wrong). Categories beyond one/few map to
 * `many`; languages without a `few` form simply never select it.
 */
export function selectPlural(
  count: number,
  keys: { one: MessageKey; few: MessageKey; many: MessageKey },
): MessageKey {
  const rule = new Intl.PluralRules(activeLanguageTag()).select(count);
  if (rule === 'one') return keys.one;
  if (rule === 'few') return keys.few;
  return keys.many;
}

/**
 * Fill `data-i18n` placeholders in static HTML: element text for
 * `data-i18n`, attributes via `data-i18n-attr="title"` pairs. Static markup
 * stays English in the source file (readable, greppable) and is swapped at
 * page load — MV3 pages have no server-side render to do it earlier.
 */
export function applyTranslations(root: ParentNode): void {
  for (const el of root.querySelectorAll<HTMLElement>('[data-i18n]')) {
    const key = el.dataset.i18n as MessageKey;
    if (en[key] !== undefined) el.textContent = t(key);
  }
  for (const el of root.querySelectorAll<HTMLElement>('[data-i18n-attr]')) {
    const pairs = (el.dataset.i18nAttr ?? '').split(';');
    for (const pair of pairs) {
      const [attr, key] = pair.split(':') as [string, MessageKey];
      if (attr && en[key] !== undefined) el.setAttribute(attr, t(key));
    }
  }
}
