/**
 * The committed machine-translated catalogs, keyed by language code.
 *
 * Each JSON is generated by `scripts/translate-catalog.ts` (never hand-run
 * at runtime, never fetched from anywhere) and holds a partial map of
 * MessageKey → translated string plus a `__meta` block the generator uses to
 * skip up-to-date entries on re-runs. `lib/i18n.ts` falls back to English
 * for anything missing, so a partial catalog degrades gracefully.
 */

import de from './locales/de.json';
import el from './locales/el.json';
import es from './locales/es.json';
import fr from './locales/fr.json';
import it from './locales/it.json';
import ja from './locales/ja.json';
import ko from './locales/ko.json';
import nl from './locales/nl.json';
import pl from './locales/pl.json';
import pt from './locales/pt.json';
import ru from './locales/ru.json';
import tr from './locales/tr.json';
import uk from './locales/uk.json';
import zh from './locales/zh.json';

import type { en } from './en';

type Catalog = Partial<Record<keyof typeof en, string>>;

/** `__meta` (generator bookkeeping) is stripped from the lookup shape here. */
function catalog(raw: Record<string, unknown>): Catalog {
  const { __meta: _meta, ...messages } = raw;
  return messages as Catalog;
}

export const locales: Record<string, Catalog> = {
  de: catalog(de),
  el: catalog(el),
  es: catalog(es),
  fr: catalog(fr),
  it: catalog(it),
  ja: catalog(ja),
  ko: catalog(ko),
  nl: catalog(nl),
  pl: catalog(pl),
  pt: catalog(pt),
  ru: catalog(ru),
  tr: catalog(tr),
  uk: catalog(uk),
  zh: catalog(zh),
};
