/**
 * Synthetic fixture generator (M2).
 *
 * Produces one compact control page per live fixture: the live page is
 * extracted into its real IdentityVector and that vector is re-rendered as a
 * page carrying only identity-bearing markup.
 *
 * Why compact pages instead of copies of the 1.7 MB originals: the originals
 * are ~1.7 MB each and would add ~20 MB of near-duplicate HTML to the repo for
 * no extra signal. Extraction against real markup is already covered by the M1
 * fixture tests; what this corpus contributes is a small, fast, fully-known
 * input for the end-to-end pipeline — real values from real pages, in a page
 * whose every field the generator knows. The generator round-trips every file
 * back through the extractor, so a compact page the extractor cannot read is a
 * generation-time failure rather than a silently useless fixture.
 *
 * History: this generator used to emit five mutated variants per base
 * (relocation, rename, rebrand, review drop, property-id swap) whose expected
 * signals were all `B.*` diff rules. The archive comparison has been removed
 * from the product, and a fixture that exercises no rule is worse than a
 * missing one — it looks like coverage. What survives is the control case, and
 * the claim it pins is the one that outlives Engine B: a well-formed listing
 * page with a complete identity and nothing wrong with it must come out GREEN.
 * That is the false-positive side of PLAN.md M7, and it is now the only side
 * this corpus can speak to.
 *
 * Run: npx vite-node scripts/make-synthetic.ts
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { JSDOM } from 'jsdom';
import { extractLiveIdentity } from '../lib/sites/booking/extract';
import type { IdentityVector } from '../lib/identity';

const ROOT = join(import.meta.dirname, '..');
const LIVE_DIR = join(ROOT, 'fixtures/live');
const OUT_DIR = join(ROOT, 'fixtures/synthetic');

/** Expected outcome when the page is run through the analysis pipeline. */
export interface SyntheticCase {
  file: string;
  description: string;
  /** Verdict the scorer must reach for this page. */
  expectVerdict: 'RED' | 'YELLOW' | 'GREEN' | 'GRAY';
}

/** Escape for a single-quoted JS string literal (utag_data style). */
function jsString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, ' ');
}

/** Escape for an HTML attribute value. */
function attr(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

/**
 * Render an IdentityVector as Booking-shaped markup: JSON-LD hotel node,
 * og:title with the marketing suffix, utag_data, map-centre vars and a
 * hotelPhotos blob — the exact carriers `lib/sites/booking/extract.ts` reads.
 */
function renderPage(v: IdentityVector, note: string): string {
  const jsonLd: Record<string, unknown> = {
    '@context': 'http://schema.org',
    '@type': 'Hotel',
    name: v.name,
    url: 'https://www.booking.com/hotel/xx/synthetic.html',
    address: { '@type': 'PostalAddress', streetAddress: v.address },
  };
  if (v.reviewScore !== undefined || v.reviewCount !== undefined) {
    jsonLd.aggregateRating = {
      '@type': 'AggregateRating',
      ...(v.reviewScore !== undefined ? { ratingValue: v.reviewScore } : {}),
      ...(v.reviewCount !== undefined ? { reviewCount: v.reviewCount } : {}),
    };
  }
  if (v.photoUrls.length > 0) jsonLd.image = v.photoUrls[0];

  const gallery = v.photoUrls
    .slice(1)
    .map((u) => `      { large_url: '${jsString(u)}' },`)
    .join('\n');

  const ogTitle = v.city ? `${v.name}, ${v.city} (updated prices 2026)` : v.name;
  const typeId = /^bkg:(\d+)$/.exec(v.propertyType ?? '')?.[1];

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<!-- SYNTHETIC FIXTURE — generated by scripts/make-synthetic.ts. ${note} -->
<title>${attr(v.name)}</title>
<meta property="og:title" content="${attr(ogTitle)}">
${v.photoUrls[0] ? `<meta property="og:image" content="${attr(v.photoUrls[0])}">` : ''}
<script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2)}
</script>
<script>
  var utag_data = {
    hotel_id: '${jsString(v.listingId ?? '')}',
    hotel_name: '${jsString(v.name)}',
    city_name: '${jsString(v.city ?? '')}',
    dest_cc: '${jsString(v.country ?? '')}',
${v.destinationId === undefined ? '' : `    ufi: '${jsString(v.destinationId)}',\n`}  };
  var b_hotel_id = '${jsString(v.listingId ?? '')}';
${typeId ? `  var accommodation_type_id = '${typeId}';` : ''}
${v.lat !== undefined ? `  var b_map_center_latitude = '${v.lat}';` : ''}
${v.lng !== undefined ? `  var b_map_center_longitude = '${v.lng}';` : ''}
  var hotelPhotos = [
${gallery}
  ];
</script>
</head>
<body>
  <div id="hp_hotel_name"><h2 class="pp-header__title">${attr(v.name)}</h2></div>
  <div data-testid="PropertyHeaderAddressDesktop-wrapper">
    <div><span><button><div>${attr(v.address)}</div></button></span></div>
  </div>
</body>
</html>
`;
}

function extractFromHtml(html: string): IdentityVector | null {
  return extractLiveIdentity(new JSDOM(html).window.document as unknown as Document, {
    now: () => new Date('2026-08-11T12:00:00Z'),
  });
}

function main(): void {
  rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const bases = readdirSync(LIVE_DIR).filter((f) => f.endsWith('.html')).sort();
  const cases: SyntheticCase[] = [];
  let failures = 0;

  for (const baseFile of bases) {
    const html = readFileSync(join(LIVE_DIR, baseFile), 'utf8');
    const baseVector = extractFromHtml(html);
    if (!baseVector) {
      console.error(`FAIL: could not extract base identity from ${baseFile}`);
      failures++;
      continue;
    }

    const stem = baseFile.replace(/\.html$/, '');
    const file = `${stem}.base.html`;
    const page = renderPage(baseVector, `base of ${baseFile}`);
    writeFileSync(join(OUT_DIR, file), page);

    // Round-trip: a synthetic page the extractor cannot read is worthless as a
    // test input, so treat it as a generation failure rather than shipping it.
    const roundTripped = extractFromHtml(page);
    if (!roundTripped) {
      console.error(`FAIL: extractor returned null for generated ${file}`);
      failures++;
      continue;
    }
    const drift: string[] = [];
    if (roundTripped.name !== baseVector.name) {
      drift.push(`name ${roundTripped.name} != ${baseVector.name}`);
    }
    if (roundTripped.city !== baseVector.city) {
      drift.push(`city ${roundTripped.city} != ${baseVector.city}`);
    }
    if (roundTripped.listingId !== baseVector.listingId) {
      drift.push(`listingId ${roundTripped.listingId} != ${baseVector.listingId}`);
    }
    if (roundTripped.destinationId !== baseVector.destinationId) {
      drift.push(`destinationId ${roundTripped.destinationId} != ${baseVector.destinationId}`);
    }
    if (baseVector.lat !== undefined && Math.abs((roundTripped.lat ?? NaN) - baseVector.lat) > 1e-6) {
      drift.push(`lat ${roundTripped.lat} != ${baseVector.lat}`);
    }
    if (roundTripped.reviewCount !== baseVector.reviewCount) {
      drift.push(`reviewCount ${roundTripped.reviewCount} != ${baseVector.reviewCount}`);
    }
    if (drift.length > 0) {
      console.error(`FAIL: round-trip drift in ${file}: ${drift.join('; ')}`);
      failures++;
      continue;
    }

    cases.push({
      file,
      description: 'Well-formed listing page with a complete identity and nothing contradictory.',
      expectVerdict: 'GREEN',
    });
  }

  writeFileSync(
    join(OUT_DIR, 'manifest.json'),
    `${JSON.stringify({ generatedFrom: 'fixtures/live', cases }, null, 2)}\n`,
  );

  console.log(`generated ${cases.length} synthetic cases from ${bases.length} bases`);
  if (failures > 0) {
    console.error(`${failures} generation failures`);
    process.exit(1);
  }
}

main();
